# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99298b695b6cd0c1b6a3eb42e003637c535c93d3aeb8d47e056bc7ebed212901bef285b946173294ddcfb72097dd60c929a50bb54cc1e312aaaf173088782b26

test:
  secret_key_base: 81c7f5c060c2d8ce86683392a8bff5c53c7aaab5ffaa6184394a2d4d2baa5045ff3d23b2a8dca04a1790f48448fb63e155fc73c389b8f31b3da4e4dd0cea7d00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 6f0cdcd221d42be6f1b700cfadd40128e50044f9f535f3ecf9bcaffeee73567810807b6f3ae8694a8791bdff3fca2c29d1e0ec32423cf0d634348bdd06ad98a7
